### ISSUE TITLE
Support triggering jobs by comments only for prod/stg

### ISSUE THREAD

**Issue by lbarcziova** [packit/packit-service#1271]
Based on a comment [here](https://github.com/packit/packit-service/pull/1256/files#r742871026).

**Comment by TomasTomecek** [comment]
@lachmanfrantisek is this fixed by #1417?

**Comment by lbarcziova** [comment]
The goal of this issue is to be able to trigger only one Packit instance for a job where more instances are configured. So if I have copr builds configured for both stg and prod and want to retrigger only prod builds, this still isn't possible if I understand it correctly.

**Comment by lbarcziova** [comment]
> What about having /packit//packit-prod for prod and /packit//packit-stg for stage? (So, from the implementation side, just replace constant with a config key and support more values instead of just one.)

Yes, I was also thinking in this way. Personally, I would have `packit` for prod and `packit-stg` for staging.

**Comment by lachmanfrantisek** [comment]
> Personally, I like `packit` for prod and `packit-stg` for staging.

So, just a single value? OK, that makes sense.
