### ISSUE TITLE
Investigate podman-compose

### ISSUE THREAD

**Issue by jpopelka** [packit/packit-service#703]
to run our [docker-compose.yml](https://github.com/packit-service/packit-service/blob/master/docker-compose.yml) without [having to tweak firewall on F32](https://github.com/docker/for-linux/issues/955#issuecomment-650977867) first.

* https://github.com/containers/podman-compose

**Comment by lachmanfrantisek** [comment]
Or, docker-compose with podman service? (Docker compatible API for podman.)

**Comment by IceWreck** [comment]
So I tested this there are three major problems:
- podman-compose has issues when containers are already running so we manually need to remove them and then run it again
- since the repo and thus cloned foldername is packit-service so it names the main pod as packit-service. But we also have a container named packit-service so there are name conflicts and we need change the name either the folder or the container.
- user: "123123" isnt supported in podmanc-compose

**Comment by jpopelka** [comment]
>     * podman-compose has issues when containers are already running so we manually need to stop and remove them and then run it again

Could this be easily solved by some make target?

>     * we need to change the name either the folder or the container

I'd change the container name to just 'service' (and 'packit-worker' to just 'worker').

>     * user: "123123" has issues with podman-compose

Openshift [runs containers as a random user ID](https://cookbook.openshift.org/users-and-role-based-access-control/why-do-my-applications-run-as-a-random-user-id.html) instead of as root so we use this to be more in sync with how the containers would be run in Openshift. But we can probably live without this.

**Comment by IceWreck** [comment]
> Could this be easily solved by some make target?
I played with this more and `podman-compose down` does the same thing (sometimes, it just feels erratic).

But in general podman-compose has a host of other issues (network related mostly). I tried it last year when I switched from Docker to Podman on my server but it had issues. I switched to using a makefile and using the podman cli directly.

And it seems unmaintained (inactive but maintained ?)

**Comment by TomasTomecek** [comment]
did you run in the rootless mode?

I'd strongly suggest run the containers as root to get rid of user and networking issues

**Comment by IceWreck** [comment]
> did you run in the rootless mode?

yes

I've managed to get the hang of networking rootless podman containers and managing uids via the cli, but still have issues when with podman-compose (which doesnt support pods afaik) or using kubernetes yaml in podman (i dont know my way round this in general)
